mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'front_left_wheel_joint'
  right_wheel: 'front_right_wheel_joint'
  publish_rate: 10.0               # default: 50
  wheel_separation : 0.60
  wheel_radius : 0.0825
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]